export const ADD_TASK_TO_LIST = 'ADD_TASK_TO_LIST';
export const REMOVE_TASK_FROM_LIST = 'REMOVE_TASK_FROM_LIST';
export const CHANGE_LISTS_ORDER = 'CHANGE_LISTS_ORDER';

export const HANDLE_AUTH = 'HANDLE_AUTH';