export const ADD_TASK_TO_LIST = 'ADD_TASK_TO_LIST';
export const REMOVE_TASK_FROM_LIST = 'REMOVE_TASK_FROM_LIST';
export const CHANGE_LISTS_ORDER = 'CHANGE_LISTS_ORDER';

export const SET_TASKS = 'SET_TASKS';
export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_DEFAULT_TASK = 'CREATE_DEFAULT_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const SORT_TASKS = 'SORT_TASKS';
export const SET_TASK_FAVORITE = 'SET_TASK_FAVORITE';

export const EDIT_LIST = 'EDIT_LIST';
export const CREATE_LIST = 'CREATE_LIST';
export const DELETE_LIST = 'DELETE_LIST';

export const HANDLE_AUTH = 'HANDLE_AUTH';
export const INIT_REQUEST = 'INIT_REQUEST';
export const INIT_BACKGROUND_REQUEST = 'INIT_BACKGROUND_REQUEST';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const ALLOW_SORT = 'ALLOW_SORT';
export const ASK_TO_CONFIRM = 'ASK_TO_CONFIRM';